# SpiNNaker Nengo Integration
# Dimension Source Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

NENGO_APP = nengo_rx
SOURCES = sdp-rx-main.c

include ../Makefile.depend
