# SpiNNaker Nengo Integration
# Ensemble Component
NENGO_APP = nengo_ensemble
SOURCES = ensemble.c neuron_lif.c encoder_recording.c recording.c pes.c voja.c filtered_activity.c ../common/input_filtering.c ../common/profiler.c
include ../Makefile.depend
