# SpiNNaker Nengo Integration
# Filter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# April 2014
# ----------------------------------------------------------------------------

NENGO_APP = nengo_filter
SOURCES = filter.c ../common/input_filtering.c

include ../Makefile.depend
