# SpiNNaker Nengo Integration
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
# ----------------------------------------------------------------------------

NENGO_APP = nengo_mc_player
SOURCES = mc_player_main.c

include ../Makefile.depend
