# SpiNNaker Nengo Integration
# (SpiNNaker to Host) Transmitter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

NENGO_APP = nengo_tx
SOURCES = sdp_tx_main.c ../common/input_filtering.c

include ../Makefile.depend
